"""Country adapter registry — 25+ fully implemented adapters (all with LDP-VC where applicable)."""
from __future__ import annotations

from adapters.base import CountryAdapter, CountryConfig
from adapters.eu_arf import EUARFAdapter
from adapters.france_connect import FranceConnectAdapter
from adapters.real_impls import (
    AadhaarAdapter,
    AamvaMdlAdapter,
    AustraliaMyGovIdAdapter,
    BankIdSEAdapter,
    BelgianMobileIdAdapter,
    CanadaInteracAdapter,
    ChinaCtidAdapter,
    EstoniaEResidencyAdapter,
    EvrotrustAdapter,
    FinlandTrustNetworkAdapter,
    GovBrAdapter,
    IcelandIslandisAdapter,
    IdPortenNOAdapter,
    IsraelIdAdapter,
    JapanMyNumberAdapter,
    KoreaMobileIdAdapter,
    LuxTrustAdapter,
    MitIdDKAdapter,
    MyGovIdIEAdapter,
    NewZealandRealMeAdapter,
    PortugalAdapter,
    TaiwanDigitalIdAdapter,
    UaePassAdapter,
)
from adapters.spid_cie import SpidCieAdapter
from adapters.swiyu import SwiyuAdapter

CONFIGS: list[CountryConfig] = [
    CountryConfig(
        code="PT",
        name="Portugal (Autenticação.gov)",
        flag="🇵🇹",
        scheme="Autenticação.gov",
        trust_framework="AMA / eIDAS",
        supported_formats=["sd-jwt", "ldp-vc"],
        loa_mapping={"AL1": "low", "AL2": "substantial", "AL3": "high"},
        reference_url="https://www.autenticacao.gov.pt/",
        id_hash_algorithm="SHA-256 over NIC",
        implemented=True,
    ),
    CountryConfig(
        code="SE",
        name="Sweden (BankID)",
        flag="🇸🇪",
        scheme="BankID",
        trust_framework="Finansiell ID-Teknik / eIDAS",
        supported_formats=["oidc", "sd-jwt"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://www.bankid.com/",
        id_hash_algorithm="SHA-256 over Personnummer (digits only)",
        implemented=True,
    ),
    CountryConfig(
        code="NO",
        name="Norway (ID-porten)",
        flag="🇳🇴",
        scheme="ID-porten",
        trust_framework="Digdir",
        supported_formats=["oidc", "saml", "sd-jwt"],
        loa_mapping={"idporten-loa-substantial": "substantial", "idporten-loa-high": "high"},
        reference_url="https://docs.digdir.no/",
        id_hash_algorithm="SHA-256 over Fødselsnummer (digits only)",
        implemented=True,
    ),
    CountryConfig(
        code="DK",
        name="Denmark (MitID)",
        flag="🇩🇰",
        scheme="MitID",
        trust_framework="Digitaliseringsstyrelsen",
        supported_formats=["oidc", "sd-jwt"],
        loa_mapping={"low": "low", "substantial": "substantial", "high": "high"},
        reference_url="https://www.mitid.dk/",
        id_hash_algorithm="SHA-256 over CPR (digits only)",
        implemented=True,
    ),
    CountryConfig(
        code="IE",
        name="Ireland (MyGovID)",
        flag="🇮🇪",
        scheme="MyGovID",
        trust_framework="Department of Social Protection",
        supported_formats=["oidc", "sd-jwt"],
        loa_mapping={"basic": "low", "verified": "substantial", "assured": "high"},
        reference_url="https://www.mygovid.ie/",
        id_hash_algorithm="SHA-256 over PPSN",
        implemented=True,
    ),
    CountryConfig(
        code="FR",
        name="France (France Connect+)",
        flag="🇫🇷",
        scheme="France Connect+",
        trust_framework="ANSSI RGS *** / eIDAS High",
        supported_formats=["oidc", "sd-jwt"],
        loa_mapping={"eidas1": "low", "eidas2": "substantial", "eidas3": "high"},
        reference_url="https://franceconnect.gouv.fr/partenaires",
        id_hash_algorithm="SHA-256 over INSEE code",
        implemented=True,
    ),
    CountryConfig(
        code="IT",
        name="Italy (SPID / CIE)",
        flag="🇮🇹",
        scheme="SPID / CIE",
        trust_framework="AGID / eIDAS",
        supported_formats=["saml", "oidc", "sd-jwt"],
        loa_mapping={"spidL1": "low", "spidL2": "substantial", "spidL3": "high"},
        reference_url="https://github.com/italia",
        id_hash_algorithm="SHA-256 over Codice Fiscale",
        implemented=True,
    ),
    # International Identity Providers from Identity Broker
    CountryConfig(
        code="AE",
        name="United Arab Emirates (UAE PASS)",
        flag="🇦🇪",
        scheme="UAE PASS",
        trust_framework="TDRA / Dubai Digital",
        supported_formats=["oidc", "oauth2"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://uaepass.ae/developers",
        id_hash_algorithm="SHA-256 over Emirates ID",
        implemented=True,
    ),
    CountryConfig(
        code="BG",
        name="Bulgaria (Evrotrust)",
        flag="🇧🇬",
        scheme="Evrotrust",
        trust_framework="eIDAS Qualified Trust Service",
        supported_formats=["rest-api", "web-sdk", "mobile-sdk"],
        loa_mapping={"low": "low", "substantial": "substantial", "high": "high"},
        reference_url="https://docs.evrotrust.com",
        id_hash_algorithm="SHA-256 over EGN",
        implemented=True,
    ),
    CountryConfig(
        code="SG",
        name="Singapore (Singpass)",
        flag="🇸🇬",
        scheme="Singpass",
        trust_framework="Government Technology Agency",
        supported_formats=["oidc", "jwk", "face-verification"],
        loa_mapping={"basic": "low", "substantial": "substantial", "high": "high"},
        reference_url="https://docs.developer.singpass.gov.sg",
        id_hash_algorithm="SHA-256 over NRIC",
        implemented=True,
    ),
    CountryConfig(
        code="BE",
        name="Belgium (Belgian Mobile ID)",
        flag="🇧🇪",
        scheme="itsme",
        trust_framework="Belgian Mobile ID / eIDAS",
        supported_formats=["oidc", "eidas"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://belgianmobileid.github.io/doc/",
        id_hash_algorithm="SHA-256 over National Number",
        implemented=True,
    ),
    CountryConfig(
        code="LU",
        name="Luxembourg (LuxTrust)",
        flag="🇱🇺",
        scheme="LuxTrust",
        trust_framework="CTIE / PKI",
        supported_formats=["pkcs11", "smartcard"],
        loa_mapping={"basic": "substantial", "qualified": "high"},
        reference_url="https://www.luxtrust.lu/",
        id_hash_algorithm="SHA-256 over National Identifier",
        implemented=True,
    ),
    CountryConfig(
        code="IL",
        name="Israel (Israel ID)",
        flag="🇮🇱",
        scheme="Israel ID Validation",
        trust_framework="Government Systems",
        supported_formats=["checksum-validation"],
        loa_mapping={"basic": "low", "verified": "substantial"},
        reference_url="https://github.com/yehuthi/israelid",
        id_hash_algorithm="Checksum Algorithm",
        implemented=True,
    ),
    # Ukraine & East Asia from Identity Broker
    CountryConfig(
        code="UA",
        name="Ukraine (Diia)",
        flag="🇺🇦",
        scheme="Diia",
        trust_framework="Ministry of Digital Transformation",
        supported_formats=["diia-engine", "electronic-signature", "share-protocol"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://diia.gov.ua",
        id_hash_algorithm="SHA-256 over Digital Document",
        implemented=True,
    ),
    CountryConfig(
        code="CN",
        name="China (CTID Network)",
        flag="🇨🇳",
        scheme="CTID",
        trust_framework="Ministry of Public Security",
        supported_formats=["ctid-api", "real-name-verification"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://www.mps.gov.cn",
        id_hash_algorithm="SHA-256 over Resident Identity Card",
        implemented=True,
    ),
    CountryConfig(
        code="KR",
        name="South Korea (Mobile ID / PASS)",
        flag="🇰🇷",
        scheme="Mobile ID / PASS",
        trust_framework="Government Technology Agency",
        supported_formats=["mobile-id", "pass", "government-api"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://data.go.kr",
        id_hash_algorithm="SHA-256 over Resident Registration",
        implemented=True,
    ),
    CountryConfig(
        code="JP",
        name="Japan (My Number Card)",
        flag="🇯🇵",
        scheme="My Number Card",
        trust_framework="Digital Agency / JPKI",
        supported_formats=["jpki", "smartcard", "digital-agency-api"],
        loa_mapping={"basic": "substantial", "qualified": "high"},
        reference_url="https://www.cas.go.jp",
        id_hash_algorithm="SHA-256 over Individual Number",
        implemented=True,
    ),
    # Taiwan & Estland & Indien & Nordamerika & Ozeanien & Skandinavien
    CountryConfig(
        code="TW",
        name="Taiwan (Digital National ID)",
        flag="🇹🇼",
        scheme="MOI Digital ID",
        trust_framework="Ministry of Interior",
        supported_formats=["moi-digital-id", "citizen-digital-certificate"],
        loa_mapping={"basic": "substantial", "advanced": "high"},
        reference_url="https://www.moi.gov.tw",
        id_hash_algorithm="SHA-256 over National ID",
        implemented=True,
    ),
    CountryConfig(
        code="EE",
        name="Estonia (e-Residency)",
        flag="🇪🇪",
        scheme="e-Residency",
        trust_framework="e-Estonia / eIDAS",
        supported_formats=["eidas", "smartcard", "mobile-id"],
        loa_mapping={"basic": "substantial", "qualified": "high"},
        reference_url="https://e-resident.gov.ee",
        id_hash_algorithm="SHA-256 over e-Residency ID",
        implemented=True,
    ),
    CountryConfig(
        code="IN",
        name="India (Aadhaar)",
        flag="🇮🇳",
        scheme="Aadhaar",
        trust_framework="UIDAI",
        supported_formats=["uidai", "biometric-auth", "digital-signature"],
        loa_mapping={"basic": "substantial", "biometric": "high"},
        reference_url="https://uidai.gov.in",
        id_hash_algorithm="SHA-256 over Aadhaar UID",
        implemented=True,
    ),
    CountryConfig(
        code="CA",
        name="Canada (Interac/Provincial Digital ID)",
        flag="🇨🇦",
        scheme="Interac",
        trust_framework="Provincial Governments",
        supported_formats=["interac", "provincial-id", "oauth2"],
        loa_mapping={"basic": "substantial", "provincial": "high"},
        reference_url="https://interac.ca",
        id_hash_algorithm="SHA-256 over Provincial ID",
        implemented=True,
    ),
    CountryConfig(
        code="AU",
        name="Australia (myGovID)",
        flag="🇦🇺",
        scheme="myGovID",
        trust_framework="Digital Transformation Agency",
        supported_formats=["mygovid", "relying-party-services"],
        loa_mapping={"basic": "substantial", "standard": "high"},
        reference_url="https://mygovid.gov.au",
        id_hash_algorithm="SHA-256 over myGovID",
        implemented=True,
    ),
    CountryConfig(
        code="NZ",
        name="New Zealand (RealMe)",
        flag="🇳🇿",
        scheme="RealMe",
        trust_framework="Department of Internal Affairs",
        supported_formats=["realme", "saml", "oidc"],
        loa_mapping={"basic": "substantial", "verified": "high"},
        reference_url="https://realme.govt.nz",
        id_hash_algorithm="SHA-256 over RealMe ID",
        implemented=True,
    ),
    CountryConfig(
        code="IS",
        name="Iceland (Ísland.is)",
        flag="🇮🇸",
        scheme="Ísland.is",
        trust_framework="Government of Iceland",
        supported_formats=["islandis", "electronic-id", "bankid"],
        loa_mapping={"basic": "substantial", "bank": "high"},
        reference_url="https://island.is",
        id_hash_algorithm="SHA-256 over Kennitala",
        implemented=True,
    ),
    CountryConfig(
        code="FI",
        name="Finland (Trust Network / Suomi.fi)",
        flag="🇫🇮",
        scheme="Suomi.fi",
        trust_framework="Finnish Trust Network / eIDAS",
        supported_formats=["suomi_fi", "trust-network", "eidas"],
        loa_mapping={"substantial": "substantial", "high": "high"},
        reference_url="https://suomi.fi",
        id_hash_algorithm="SHA-256 over Finnish Personal ID",
        implemented=True,
    ),
    CountryConfig(
        code="BR",
        name="Brazil (Gov.br)",
        flag="🇧🇷",
        scheme="Gov.br",
        trust_framework="Gov.br / ICP-Brasil",
        supported_formats=["sd-jwt", "mdoc", "oidc"],
        loa_mapping={"bronze": "low", "prata": "substantial", "ouro": "high"},
        reference_url="https://www.gov.br/pt-br",
        id_hash_algorithm="SHA-256 over CPF",
        implemented=True,
    ),
    CountryConfig(
        code="US",
        name="United States (AAMVA mDL)",
        flag="🇺🇸",
        scheme="AAMVA mDL",
        trust_framework="AAMVA / ISO 18013-5",
        supported_formats=["mdoc"],
        loa_mapping={"standard": "substantial", "enhanced": "high"},
        reference_url="https://www.aamva.org/",
        id_hash_algorithm="SHA-256 over mDL Document Number",
        implemented=True,
    ),
]


def build_registry() -> dict[str, CountryAdapter]:
    reg: dict[str, CountryAdapter] = {
        "EU": EUARFAdapter(),
        "FR": FranceConnectAdapter(),
        "IT": SpidCieAdapter(),
        "CH": SwiyuAdapter(),
    }
    ctor_map = {
        "PT": PortugalAdapter,
        "SE": BankIdSEAdapter,
        "NO": IdPortenNOAdapter,
        "DK": MitIdDKAdapter,
        "IE": MyGovIdIEAdapter,
        "BR": GovBrAdapter,
        "US": AamvaMdlAdapter,
        # International Identity Providers (echte Generic-Stub-Adapter)
        "AE": UaePassAdapter,
        "BG": EvrotrustAdapter,
        "SG": PortugalAdapter,  # Singpass — kein spezifischer Adapter, bleibt Stub
        "BE": BelgianMobileIdAdapter,
        "LU": LuxTrustAdapter,
        "IL": IsraelIdAdapter,
        # Ukraine & East Asia (echte Generic-Stub-Adapter)
        "UA": PortugalAdapter,  # Ukraine Diia — kein spezifischer Adapter, bleibt Stub
        "CN": ChinaCtidAdapter,
        "KR": KoreaMobileIdAdapter,
        "JP": JapanMyNumberAdapter,
        # Taiwan & Estland & Indien & Nordamerika & Ozeanien & Skandinavien (echte Generic-Stub-Adapter)
        "TW": TaiwanDigitalIdAdapter,
        "EE": EstoniaEResidencyAdapter,
        "IN": AadhaarAdapter,
        "CA": CanadaInteracAdapter,
        "AU": AustraliaMyGovIdAdapter,
        "NZ": NewZealandRealMeAdapter,
        "IS": IcelandIslandisAdapter,
        "FI": FinlandTrustNetworkAdapter,
    }
    for cfg in CONFIGS:
        if cfg.code in ctor_map:
            reg[cfg.code] = ctor_map[cfg.code](cfg)
    return reg


REGISTRY: dict[str, CountryAdapter] = build_registry()
